app/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views

app_name = "accounts"  # pylint: disable=C0103; # noqa
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="registration/login.html", form_class=views.LoginForm
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

app/api/urls.py
# Copyright: (c) 2019, Michele Valsecchi <https://gitlab.com/micheleva>
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from django.urls import path, include

app_name = "api"  # pylint: disable=C0103; # noqa
urlpatterns = [
    path("v1/", include("api.v1.urls")),
    path("alpha/", include("api.alpha.urls")),
]

app/api/v1/urls.py
# Copyright: (c) 2019, Michele Valsecchi <https://gitlab.com/micheleva>
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from django.urls import path

from api.v1.views import views
from api.v1.views import account_views
from api.v1.views import asset_views
from api.v1.views import budget_views
from api.v1.views import category_views
from api.v1.views import dividend_views
from api.v1.views import expense_views
from api.v1.views import income_views
from api.v1.views import income_category_view
from api.v1.views import monthly_balance_category_views
from api.v1.views import monthly_balance_views
from api.v1.views import goal_views
from api.v1.views import obligation_views
from api.v1.views import saving_category_views
from api.v1.views import spending_limit_views

app_name = "v1"  # pylint: disable=C0103; # noqa
urlpatterns = [
    # Function views
    path(
        "expenses/made_often",
        expense_views.get_expenses_made_often,
        name="expenses_made_often",
    ),
    path(
        "monthly_balances_and_assets",
        views.monthly_balances_and_assets,
        name="monthly_balances_and_assets",
    ),
    path(
        "accounts/create_list",
        account_views.AccountList.as_view(),
        name="accounts",
    ),
    path(
        "accounts/update/<int:pk>/",
        account_views.AccountDetail.as_view(),
        name="account",
    ),
    path("assets", asset_views.AssetsList.as_view(), name="assets"),
    path(
        "assets/create",
        asset_views.AssetsCreate.as_view(),
        name="asset_create",
    ),
    path(
        "assets/list_dates", asset_views.get_assets_dates, name="assets_dates"
    ),
    path(
        "assets/delete",
        asset_views.BulkDeleteAssets.as_view(),
        name="bulk-delete-assets",
    ),
    path("dividends", dividend_views.DividendList.as_view(), name="dividends"),
    path(
        "dividends/aggregate",
        dividend_views.DividendsAggregateList.as_view(),
        name="dividends_aggregate",
    ),
    path(
        "dividends/aggregate-by-symbol",
        dividend_views.DividendsAggregateListBySymbol.as_view(),
        name="dividends_aggregate_by_symbol",
    ),
    path(
        "dividends/create",
        dividend_views.DividendList.as_view(),
        name="dividends_create",
    ),
    path(
        "dividends/delete",
        dividend_views.DividendsDeleteAll.as_view(),
        name="dividends_delete",
    ),
    path(
        "spending-limits",
        spending_limit_views.SpendingLimitList.as_view(),
        name="spending_limits",
    ),
    path(
        "spending-limits/<int:pk>",
        spending_limit_views.SpendingLimitDetail.as_view(),
        name="spending_limit",
    ),
    path("goals/special", goal_views.special_goal_list, name="special_goals"),
    # Class views
    path(
        "categories", category_views.CategoryList.as_view(), name="categories"
    ),
    # FIXME: this should end with a slash, and change react api call to patch
    # to include a trailing slash
    path(
        "category/<int:pk>",
        category_views.CategoryDetail.as_view(),
        name="category_detail",
    ),
    path("goals", goal_views.GoalList.as_view(), name="goals"),
    path(
        "goals/<int:pk>/", goal_views.GoalDetail.as_view(), name="goal_detail"
    ),
    path(
        "obligations/",
        obligation_views.ObligationViewSet.as_view(
            {"get": "list", "post": "create"}
        ),
        name="obligations",
    ),
    path(
        "obligations/<int:pk>/",
        obligation_views.ObligationViewSet.as_view(
            {"get": "retrieve", "patch": "update", "delete": "destroy"}
        ),
        name="obligation_detail",
    ),
    path(
        "obligations-changes/",
        obligation_views.ObligationPaymentChangeViewSet.as_view(
            {"get": "list", "post": "create"}
        ),
        name="obligationpaymentchanges",
    ),
    path(
        "obligations-changes/<int:pk>/",
        obligation_views.ObligationPaymentChangeViewSet.as_view(
            {"get": "retrieve", "put": "update", "delete": "destroy"}
        ),
        name="obligationpaymentchange_detail",
    ),
    path(
        "monthly_balance_categories",
        monthly_balance_category_views.MonthlyBalanceCategoryList.as_view(),
        name="monthly_balance_categories",
    ),
    path(
        "monthly_balance_category/<int:pk>/",
        monthly_balance_category_views.MonthlyBalanceCategoryDetail.as_view(),
        name="monthly_balance_category",
    ),
    path(
        "monthly_balances",
        monthly_balance_views.MonthlyBalanceList.as_view(),
        name="monthly_balances",
    ),
    path(
        "monthly_balances/<int:pk>/",
        monthly_balance_views.MonthlyBalanceDetail.as_view(),
        name="monthly_balances",
    ),
    path(
        "monthly_balances/create-update",
        monthly_balance_views.MonthlyBalanceCreateOrUpdate.as_view(),
        name="monthly_balance_category_create_or_update",
    ),
    path(
        "expenses/create-list",
        expense_views.ExpenseList.as_view(),
        name="expenses",
    ),
    path(
        "expenses/<int:pk>/",
        expense_views.ExpenseDetail.as_view(),
        name="expense",
    ),
    path(
        "expenses/aggregate/by_month",
        expense_views.ExpenseListAggregate.as_view(),
        name="expenses_aggregate_by_month",
    ),
    path(
        "expenses/aggregate/by_category",
        expense_views.ExpenseListAggregateByCategory.as_view(),
        name="expenses_aggregate_by_cat",
    ),
    path(
        "income-categories",
        income_category_view.IncomeCategoryList.as_view(),
        name="income_categories",
    ),
    path(
        "income-categories/<int:pk>/",
        income_category_view.IncomeCategoryDetail.as_view(),
        name="income_category",
    ),
    path("incomes", income_views.IncomeList.as_view(), name="incomes"),
    path(
        "incomes/aggregate",
        income_views.IncomeListAggregate.as_view(),
        name="incomes_aggregate",
    ),
    path(
        "incomes/<int:pk>/", income_views.IncomeDetail.as_view(), name="income"
    ),
    path(
        "savingcategories",
        saving_category_views.SavingCategoryList.as_view(),
        name="savingcategories",
    ),
    path(
        "savingcategory/<int:pk>/",
        saving_category_views.SavingCategoryDetails.as_view(),
        name="savingcategory",
    ),
    path("budgets", budget_views.BudgetList.as_view(), name="budgets"),
    path(
        "budgets/<int:pk>/", budget_views.BudgetDetail.as_view(), name="budget"
    ),
    path(
        "budgets/yearly-aggregate/<int:year>/",
        budget_views.MonthlyBudgetSumAPI.as_view(),
        name="budget-yearly-aggregate",
    ),
]

app/budgeteer/urls.py
# pylint: disable=C0103
import os
from django.urls import path, include
from django.urls import re_path

# Note: Regex /?P<date>(19|20)[0-9]{2}-(0[1-9]|1[012]))/
# allow only dates between 1900-01 and 2099-12
# Warning: month is always two digits (i.e. Jan -> '01', not '1')
urlpatterns = [
    path("", include("budgets.urls")),
    path("api/", include("api.urls", namespace="api")),
    path("accounts/", include("accounts.urls")),
]

if "y" in os.getenv("DJANGO_DEBUG_MODE"):
    import debug_toolbar

    urlpatterns = [
        re_path(r"^__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

handler403 = "budgets.views.permission_denied_view"
# TODO:Need to update tests to stop checking for 404
# and check for error message instead
# handler404 = 'budgets.views.page_not_found_view'

app/budgets/urls.py
# Copyright: (c) 2019, Michele Valsecchi <https://gitlab.com/micheleva>
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from django.urls import include
from django.urls import path
from django.urls import re_path
from django.templatetags.static import static
from django.views.generic.base import RedirectView

from budgets import views

app_name = "budgets"  # pylint: disable=C0103; # noqa

urlpatterns = [
    # Until we remove the old non-react pages let's keep both / and /spa
    # as entry point for the react app
    path("", views.spa, name="home"),
    re_path("app.*", views.spa, name="spa"),
    # TODO: fix me, this is an horrible hack for favico
    re_path(".*favicon.ico", RedirectView.as_view(url=static("favicon.ico"))),
    path("landing_page", views.landing_page, name="landing_page"),
]

app/api/v1/views/budget_views.py
# Copyright: (c) 2025, Michele Valsecchi <https://gitlab.com/micheleva>
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# pylint: disable=E1101,W0611,R0901

import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.db.utils import IntegrityError

from rest_framework import generics
from rest_framework import status
from rest_framework.permissions import SAFE_METHODS
from rest_framework.response import Response

from budgets.models import Budget
from budgets.serializers import BudgetSerializer
from budgets.serializers import BudgetSerializerAllowOnlyAmountsUpdate
from budgets.serializers import BudgetSerializerWithCategory
from budgets.serializers import YearlyAggregateBudgetSerializer


###############################################################################
# API: Class based
###############################################################################

logger = logging.getLogger(__name__)


class BudgetList(generics.ListCreateAPIView):
    """
    View to list and create Budgets
    """

    def get_serializer_class(self):
        # BudgetSerializerWithCategoryOrSedAsideCategory has the
        # Category/SavingCategory as nested object while BudgetSerializer
        # does not, as its used on create/edit
        return (
            BudgetSerializerWithCategory
            if self.request.method in SAFE_METHODS
            else BudgetSerializer
        )

    def get_queryset(self):
        filters = {"created_by": self.request.user}
        # Only filter by year and month if, at least, year is present
        # If only year is passed, automatically only return Budgets having
        # month=Null. If both year and month are passed, filter by both
        if (
            self.request.GET.get("year", None)
            and str(self.request.GET.get("year", None)).isdigit()
        ):
            filters["year"] = self.request.GET.get("year")
            if (
                self.request.GET.get("month", None)
                and str(self.request.GET.get("month", None)).isdigit()
            ):
                filters["month"] = self.request.GET.get("month")
            else:
                filters["month__isnull"] = True

        return (
            Budget.objects.select_related("category", "savingcategory")
            .filter(**filters)
            .order_by("year", "month", "category_id", "savingcategory", "id")
        )

    def perform_create(self, serializer):
        try:
            return serializer.save(created_by=self.request.user)
        except IntegrityError as e:
            msg_to_devs = (
                "Exception catched in BudgetList.perform_create(),"
                " user ID: "
                f"{self.request.user.id}. Alert the devs, we have a "
                "constraint not working properly"
            )
            logger.critical(msg_to_devs)
            logger.critical(e)
            msg = [
                "Generic error thrown while creating the Budget. "
                "Refer to the web container logs if you're the admin."
            ]
            return Response(
                {"non_field_errors": msg},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if not serializer.is_valid(raise_exception=False):
            return Response(
                serializer.errors, status=status.HTTP_400_BAD_REQUEST
            )

        self.perform_create(serializer)
        return Response(serializer.data, status=status.HTTP_201_CREATED)


# NOTE: we intentionally do not allow deletion: users should set the amount to 0 instead
class BudgetDetail(LoginRequiredMixin, generics.RetrieveUpdateAPIView):
    """
    View to list, update, delete a single expense
    """

    def get_serializer_class(self):
        # BudgetSerializerWithCategoryOrSedAsideCategory has the
        # Category/SavingCategory as nested object while
        # BudgetSerializerAllowOnlyAmountsUpdate does not, as its used on
        # create/edit
        return (
            BudgetSerializerWithCategory
            if self.request.method in SAFE_METHODS
            else BudgetSerializerAllowOnlyAmountsUpdate
        )

    def get_queryset(self):
        filters = {
            "created_by": self.request.user,
        }
        return (
            Budget.objects.select_related("category", "savingcategory")
            .filter(**filters)
            .order_by("year", "month", "id")
        )

    # BUGFIX-257 Shouldn't we have this logic inside update() and
    # use perform_update() to  simply inject the ownership instead?
    # See https://stackoverflow.com/a/69395096 on create vs perform_create
    # Override perform_create() when you want to change the "behind-the-scenes"
    # behavior of how your object is created. For example, performing some
    # extra actions before or after the object is created.
    # Override create() when you want to modify the response.For example, if
    # you want to re-structure the response, add extra data, extra headers,etc.
    def perform_update(self, serializer):
        if not serializer.is_valid(raise_exception=False):
            return Response(
                serializer.errors, status=status.HTTP_400_BAD_REQUEST
            )
        # NOTE: no need to check category ownwership here as
        # MonthlyBalanceSerializerWithNestedCategory has
        # category/savingcategory set to read only
        try:
            # IMPORTANT: do not inject the ownership on update.
            # It introduces un-necessary risks
            return serializer.save()
        except IntegrityError as e:
            logger.error(e)
            msg_to_devs = (
                "Exception catched in BudgetDetail.perform_update(),"
                f" user ID: {self.request.user.id}. Alert the devs,"
                " we have a constraint not working properly"
            )
            logger.critical(msg_to_devs)
            logger.critical(e)
            msg = [
                (
                    "Generic error thrown while updating the Budget. "
                    "Refer the web container logs if you're the admin"
                )
            ]
            return Response(
                {"non_field_errors": msg},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )


class MonthlyBudgetSumAPI(generics.ListAPIView):
    serializer_class = YearlyAggregateBudgetSerializer

    def get_queryset(self):
        year = self.kwargs.get("year")
        user = self.request.user
        queryset = (
            Budget.objects.filter(
                created_by=user, year=year, month__isnull=False
            )
            .values("category")
            .annotate(sum_amount=Sum("amount"))
        )

        return list(queryset)

    def list(self, request, *args, **kwargs):
        res = self.get_queryset()
        response_data = {
            "results": res,
            "count": len(res),
        }
        return Response(response_data)

app/budgets/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="manifest" href="/site.webmanifest">
    <title>{% block title %}{% endblock %}</title>
    {%if dark_theme %}
    <link href="{% static 'bootstrap/css/dark_bootstrap.css' %}" rel="stylesheet" media="all">
    {% else %}
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet" media="all">
    {% endif %}
    {% block preload_js %}{% endblock %}
  </head>

  <body>
    <div class="container-fluid">
      {% include "navbar.html" %}

      {% block content %}
      {% endblock %}
    </div>

    <div class="col-md-12">
      <div class="text-center">
        <footer class="page-footer font-small">
          <span id="footer_text">
            📈 Budgeteer 💰
          </span>
        </footer>
      </div>
    </div>

  </body>

</html>

app/budgets/templates/edit_monthly_balances.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Edit monthly budget{% endblock %}

{% block content %}

<div class="row">
  <div  class="col">
    <h5 id="id_current_month_date">Monthly balance editing...</h5>
    <hr>
    <form method="POST" action="{% url 'budgets:edit_monthly_balance' id  %}">
        <!-- FIXME: As this form contains the previously entered data
             We need to hide the errors, in order to be able
            to show them all at once, after the submit button -->
        {% for field in form %}
              {{ field.label_tag }} {{ field }}
        {% endfor %}
      <input type="submit" id="id_submit" value="Submit">

      {% if errors %}
          <div>{{ errors }}</div>
      {% endif %}

      {% csrf_token %}
    </form>
  </div>
</div>

{% endblock %}


{{ form }}

app/budgets/templates/home.html
{% extends 'base.html' %}
{% load budgets_tags %}
{% load humanize %}
{% load staticfiles %}

{% block title %}Budgeteer{% endblock %}

{% block content %}

<div class="row">
    <div  class="col">
      <h3>General recap</h3>
      <h5>Last two months</h5>
      <div class="table-responsive-md table-sm">
        <table class="table" id="id_recap">
          <tr>
              <td>Starting balance</td>
              <td>{{ currency }} {{ starting_balance | intcomma }}</td>
          </tr>
          <tr>
              <td><b>Current balance</b></td>
              <td><b>{{ currency }} {{ current_balance | intcomma }}</b></td>
          </tr>
          <tr>
              <td>Result</td>
              {% if current_balance and starting_balance%}
                <td class="{% if two_months_diff < 0 %}text-danger{% else %}text-success{% endif %}">
                  {{ currency }}{% if two_months_diff > 0 %}+{% endif %}{{ two_months_diff | intcomma }}
                  ({% if two_months_diff <= 0 %}{% else %}+{% endif %}{{ two_months_diff_perc }}%)
                </td>
              {% else %}
                <td>-</td>
              {% endif %}
              <!-- TODO: check if current_balance is existing or not -> lead to create balance for this month -->
          </tr>
        </table>
      </div>
    </div>
    {% if goals %}
      <div  class="col">
        <h3>Goals</h3>
        <h5>&nbsp;</h5> <!-- HACK: Empty line to line up vertically the two tables -->
        <div class="table-responsive-md table-sm">
          <table class="table" id="id_recap">
            <tr>
              <th>Goal</th>
              <th>Amount</th>
              <th>Months to go</th>
            </tr>
            {% for goal in goals %}
              <tr>
                <td>{{ goal.text }}</td>
                <td>{{ currency}} {{ goal.amount | intcomma }}</td>
                {% if goal.months_to_go is None %}
                  <td class="text-danger">Negative or static balance: N/A</td>
                {% elif goal.months_to_go > 0 %}
                  <td>{{ goal.months_to_go }}</td>
                {% else %}
                  <td class="text-success">Goal already achieved!</td>
                {% endif %}
              </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    {% endif %}
</div>

<div class="row">
    {% if bar_graph %}
    <div  class="col">
      <img src="data:image/png;base64,{{ bar_graph }}" class="img-fluid" alt="Bar graph" {% if not pie_graph %}width="100%"{% endif%}>
    </div>
    {% endif %}
    {% if pie_graph %}
      <div class="col">
        <img src="data:image/png;base64,{{ pie_graph }}" class="img-fluid" alt="Pie graph">
      </div>
    {% endif %}
</div>

<div class="row">
  {% if current_mb %}
    <div  class="col">
      <h6><b>Current</b> month situation</h6>
      <table class="table table-responsive-md table-sm" id="id_monthly_balances">
        <tr>
          <th>Category</th>
          <th>Amount</th>
        </tr>

        {% for monthly_balance in current_mb %}
          <tr>
            <td>{{ monthly_balance.category.text }}</td>
            <td>{{ currency}}
              <!-- TODO: check for foreign currencies. Factor in the exchange rate, display correct currency symbol -->
              {% if monthly_balance.actual_amount %}
                  {{ monthly_balance.actual_amount | intcomma }} ( {{ monthly_balance.amount | intcomma }} )</td>
              {% else %}
                  {{ monthly_balance.amount | intcomma }}</td>
              {% endif %}
          </tr>
        {% endfor %}

          <tr>
            <td><b>Total</b></td>
            <td><b>{{ currency}} {{ current_mb_total | intcomma }}</b></td>
          </tr>
      </table>
    </div>
  {% endif %}

  {% if prev_mb %}
  <div  class="col">
    <h6><b>Previous</b> month situation</h6>
    <table class="table table-responsive-md table-sm" id="id_monthly_balances">
      <tr>
        <th>Category</th>
        <th>Amount</th>
      </tr>

      {% for monthly_balance in prev_mb %}
        <tr>
          <td>{{ monthly_balance.category.text }}</td>
          <td>{{ currency}}
            <!-- TODO: check for foreign currencies. Factor in the exchange rate, display correct currency symbol -->
            {% if monthly_balance.actual_amount %}
                {{ monthly_balance.actual_amount | intcomma }} ( {{ monthly_balance.amount | intcomma }} )</td>
            {% else %}
                {{ monthly_balance.amount | intcomma }}</td>
            {% endif %}
        </tr>
      {% endfor %}

        <tr>
          <td><b>Total</b></td>
          <td><b>{{ currency}} {{ prev_mb_total | intcomma }}</b></td>
        </tr>
    </table>
  </div>
  {% endif %}
  <div  class="col">
    <div id="root"></div>
    {% if webpack == 'y' %}
      <script src="http://localhost:4000/bundle.js"></script>
    {% else %}
      <script src="{% static 'js/bundle.js' %}"></script>
    {% endif %}
  </div>
</div>

{% endblock %}

app/budgets/templates/landing_page.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Budgeteer</title>
    {%if dark_theme %}
    <link href="{% static 'bootstrap/css/dark_bootstrap.css' %}" rel="stylesheet" media="all">
    {% else %}
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet" media="all">
    {% endif %}
    {% block preload_js %}{% endblock %}
  </head>

  <body>

  <div class="container text-center">

    <header class="jumbotron my-4">
      <h1 class="display-3">Budgeteer</h1>

      <p class="lead">
        Household Budget Management made simple 📈💰
      </p>
      <a href="https://gitlab.com/micheleva/budgeteer" class="btn btn-primary btn-lg">Look at the source</a>

    </header>


<!-- Theme https://github.com/StartBootstrap/startbootstrap-heroic-features -->
<!-- License: MIT -->
    <div class="row text-center">

      <div class="col-lg-4 col-md-4 mb-3">
        <div class="card h-100">
          <div class="card-body">
            <h4 class="card-title">Existing user</h4>
            <p class="card-text">Login using your credentials from here!</p>
          </div>
          <div class="card-footer">
            <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>
          </div>
        </div>
      </div>

      {% if signup_enabled %}
      <div class="col-lg-4 col-md-4 mb-3">
        <div class="card h-100">
          <div class="card-body">
            <h4 class="card-title">New user</h4>
            <p class="card-text">No email needed, no tracking, no ads. <b>Make sure to harden the app if you expose it to the internet 😜</b></p>
          </div>
          <div class="card-footer">
            <a href="{% url 'accounts:signup' %}" class="btn btn-primary">Signup</a>
          </div>
        </div>
      </div>
      {% endif %}

      <div class="col-lg-4 col-md-4 mb-3">
        <div class="card h-100">
          <div class="card-body">
            <h4 class="card-title">I've found a bug!🐞</h4>
            <p class="card-text">Thank you very much! Please post a minimal reproducer, with the expected behaviour, the actual behaviour and the version you're using (i.e. the git commit hash you've checked out at)</p>
          </div>
          <div class="card-footer">
            <a href="https://gitlab.com/micheleva/budgeteer/-/issues/new" class="btn btn-primary">Open a ticket</a>
          </div>
        </div>
      </div>

    </div>

  </div>

  <div class="col-md-12">
    <div class="text-center">
      <footer class="page-footer font-small">
        <span id="footer_text">
          📈 Budgeteer 💰
        </span>
      </footer>
    </div>
  </div>

  </body>


</html>

app/budgets/templates/navbar.html
{% block navbar %}
<!-- TODO: the navbar is not responsive, fix me -->
<header class="navbar navbar-expand  flex-column flex-md-row bd-navbar">

  <div class="navbar-nav-scroll">
    <ul class="navbar-nav bd-navbar-nav flex-row">
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'budgets:home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'budgets:spa' %}">Home (spa)</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'budgets:categories' %}">Categories</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'budgets:monthly_budgets' %}">Monthly Budgets</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'budgets:expenses' %}">Expenses</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'budgets:income_categories' %}">Income Categories</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'budgets:incomes' %}">Incomes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'budgets:monthly_balance_categories' %}">Monthly balance category </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'budgets:monthly_balances' %}">Monthly balances</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'budgets:goals' %}">Goals</a>
      </li>
      {% if not request.user.is_anonymous %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">(Not {{ request.user }}?) Logout</a>
      </li>
      {% endif %}
    </ul>
  </div>

</header>
{% endblock %}

app/budgets/templates/spa.html
{% extends 'no_nav_bar_base.html' %}
{% load budgets_tags %}
{% load humanize %}
{% load staticfiles %}

{% block title %}Budgeteer{% endblock %}

{% block content %}

<div class="row">
  <div  class="col">
    <div id="root"></div>
    {% if webpack == 'y' %}
      <script src="http://localhost:4000/bundle.js"></script>
    {% else %}
      <script src="{% static 'js/bundle.js' %}"></script>
    {% endif %}
  </div>
</div>

{% endblock %}